### ISSUE TITLE
use unit test error

### ISSUE THREAD

**Issue by liuchenx** [googlesamples/android-architecture#117]
java.lang.NullPointerException
	at com.example.android.architecture.blueprints.todoapp.tasks.TasksPresenter.loadTasks(TasksPresenter.java:106)
	at com.example.android.architecture.blueprints.todoapp.tasks.TasksPresenter.loadTasks(TasksPresenter.java:83)
	at com.example.android.architecture.blueprints.todoapp.tasks.TasksPresenterTest.loadAllTasksFromRepositoryAndLoadIntoView(TasksPresenterTest.java:82)

**Comment by JoseAlcerreca** [comment]
Can you add more details? Branch?

**Comment by liuchenx** [comment]
Branch: dev-todo-mvp-rxjava

run: Test/com.example.android.architecture.blueprints.todoapp.tasks.TasksPresenterTest

**Comment by JoseAlcerreca** [comment]
rx-java is in dev.
