### ISSUE TITLE
[todo-mvp-loaders]TasksRepository is not thread-safe

### ISSUE THREAD

**Issue by kyle-ilantzis** [googlesamples/android-architecture#275]
Like https://github.com/googlesamples/android-architecture/issues/179 TasksLoader and TaskLoader run in a thread pool, so should synchronized the visit of shared resource (e.g., TasksRepository.mCacheTasks)

**Comment by swankjesse** [comment]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
	at java.util.LinkedHashMap.addNewEntry(LinkedHashMap.java:195)
	at java.util.HashMap.put(HashMap.java:403)
	at com.example.android.architecture.blueprints.todoapp.data.source.TasksRepository#saveTask.run(TasksRepository.java:189)
```

**Comment by JoseAlcerreca** [comment]
The loaders branch is deprecated, so closing.
