### ISSUE TITLE
[todo-mvp-clean] crashed when run paralleles usecase

### ISSUE THREAD

**Issue by thaihuynhxyz** [googlesamples/android-architecture#487]
I put  `Thread.sleep(TimeUnit.SECONDS.toMillis(10));` in CompleteTask use case, then mark complete > 6 tasks -> crashed
java.util.concurrent.RejectedExecutionException: Task com.example.android.architecture.blueprints.todoapp.UseCaseHandler$1@bcd68f0 rejected from java.util.concurrent.ThreadPoolExecutor@60efe69[Running, pool size = 4, active threads = 4, queued tasks = 2, completed tasks = 11]

**Comment by JoseAlcerreca** [comment]
Need more details

**Comment by thaihuynhxyz** [comment]
slow down your CompleteTask useCase. then run this Test
@Test
    public void test() throws Exception {
        createTask(TITLE1, DESCRIPTION);
        for(int i = 0; i < 10; i++) createTask("title" + i, DESCRIPTION);


        // Verify task is displayed on screen
        onView(withItemText(TITLE1)).check(matches(isDisplayed()));
        for(int i = 0; i < 10; i++) clickCheckBoxForTask("title" + i);
    }
in TasksScreenTest you will get crash
Started running tests

android.support.test.espresso.PerformException: Error performing 'single click - At Coordinates: 83, 1645 and precision: 16, 16' on view 'Animations or transitions are enabled on the target device.
For more info check: http://goo.gl/qVu1yV

(with id: com.example.android.architecture.blueprints.todomvpclean.mock:id/complete and has sibling: with text: is "title6")'.
at android.support.test.espresso.PerformException$Builder.build(PerformException.java:84)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:81)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:52)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at android.support.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:167)
at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:110)
at com.example.android.architecture.blueprints.todoapp.tasks.TasksScreenTest.clickCheckBoxForTask(TasksScreenTest.java:533)
at com.example.android.architecture.blueprints.todoapp.tasks.TasksScreenTest.test(TasksScreenTest.java:181)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
Caused by: java.util.concurrent.RejectedExecutionException: Task com.example.android.architecture.blueprints.todoapp.UseCaseHandler$1@29b3887 rejected from java.util.concurrent.ThreadPoolExecutor@6ba63b4[Running, pool size = 4, active threads = 4, queued tasks = 2, completed tasks = 23]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
at com.example.android.architecture.blueprints.todoapp.UseCaseThreadPoolScheduler.execute(UseCaseThreadPoolScheduler.java:51)
at com.example.android.architecture.blueprints.todoapp.UseCaseHandler.execute(UseCaseHandler.java:45)
at com.example.android.architecture.blueprints.todoapp.tasks.TasksPresenter.completeTask(TasksPresenter.java:187)
at com.example.android.architecture.blueprints.todoapp.tasks.TasksFragment$5.onCompleteTaskClick(TasksFragment.java:220)
at com.example.android.architecture.blueprints.todoapp.tasks.TasksFragment$TasksAdapter$1.onClick(TasksFragment.java:418)
at android.view.View.performClick(View.java:6294)
at android.widget.CompoundButton.performClick(CompoundButton.java:134)
at android.view.View$PerformClick.run(View.java:24770)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:160)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:472)
at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:419)
at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:240)
at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:138)
at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:119)
at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:153)
at android.support.test.espresso.action.Tap.access$100(Tap.java:33)
at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:44)
at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:128)
at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:241)
at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Tests ran to completion.

**Comment by thaihuynhxyz** [comment]
please tell me if you don't care this issue
