### ISSUE TITLE
error when adding task

### ISSUE THREAD

**Issue by sfabriece** [googlesamples/android-architecture#88]
I'm testing the app and getting an arror when adding a task

my phone is galaxy s3
android: 5.0.1
android studio 2.2 preview
gradle: 2.2.alpha

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.android.architecture.blueprints.todomvpdagger.mock, PID: 8462
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.architecture.blueprints.todomvpdagger.mock/com.example.android.architecture.blueprints.todoapp.addedittask.AddEditTaskActivity}: android.view.InflateException: Binary XML file line #30: Error inflating class EditText
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
                      at android.app.ActivityThread.access$900(ActivityThread.java:177)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:5951)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                   Caused by: android.view.InflateException: Binary XML file line #30: Error inflating class EditText
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                      at com.example.android.architecture.blueprints.todoapp.addedittask.AddEditTaskFragment.onCreateView(AddEditTaskFragment.java:99)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
                      at android.app.Activity.performStart(Activity.java:6329)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:145) 
                      at android.app.ActivityThread.main(ActivityThread.java:5951) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/abc_edit_text_material.xml from drawable resource ID #0x7f020015
                      at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
                      at android.content.res.Resources.loadDrawable(Resources.java:3603)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
                      at android.view.View.<init>(View.java:3957)
                      at android.widget.TextView.<init>(TextView.java:998)
                      at android.widget.EditText.<init>(EditText.java:74)
                      at android.widget.EditText.<init>(EditText.java:70)
                      at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
                      at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:56)
                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
                      at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980)
                      at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039)
                      at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                      at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:181)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                      at com.example.android.architecture.blueprints.todoapp.addedittask.AddEditTaskFragment.onCreateView(AddEditTaskFragment.java:99) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
                      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601) 
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234) 
                      at android.app.Activity.performStart(Activity.java:6329) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
                      at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:145) 
                      at android.app.ActivityThread.main(ActivityThread.java:5951) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #24: <nine-patch> requires a valid 9-patch source image
                      at android.graphics.drawable.NinePatchDrawable.updateStateFromTypedArray(NinePatchDrawable.java:445)
                    at android.graphics.draw
```

**Comment by JoseAlcerreca** [comment]
This is todo-mvp-dagger.

I cannot reproduce. Can you please confirm the gradle plugin version that you're using?

**Comment by sfabriece** [comment]
![gradle_version](https://cloud.githubusercontent.com/assets/3108592/15505678/c3683bf2-21c4-11e6-85af-dcd85efa8e84.png)
 still getting the same error.
